version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: sufal_physics_forum_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sufal_physics_forum
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
